version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - CUCM_HOST=${CUCM_HOST}
      - CUCM_USER=${CUCM_USER}
      - CUCM_PASS=${CUCM_PASS}
      - CUCM_VERSION=${CUCM_VERSION}
      - PORT=3000
      - DATACONTAINERIDENTIFIERTAILS=_data
    restart: unless-stopped
    volumes:
      - ./.env:/usr/src/app/.env:ro