services:
  cucm-rest-api:
    image: ghcr.io/sieteunoseis/cucm-soap-rest:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - CUCM_HOST=${CUCM_HOST}
      - CUCM_USER=${CUCM_USER}
      - CUCM_PASS=${CUCM_PASS}
      - CUCM_VERSION=${CUCM_VERSION}
      - PORT=3000
      - DATACONTAINERIDENTIFIERTAILS=_data
      - AUTO_SAVE_EXAMPLES=${AUTO_SAVE_EXAMPLES:-false}
      - AUTO_SAVE_EXPLORER=${AUTO_SAVE_EXPLORER:-false}
    restart: always
    volumes:
      # Mount examples directory to allow customization without rebuilding the image
      - ./examples:/usr/src/app/src/examples