services:
  cucm-rest-api:
    container_name: cucm-rest-api
    image: ghcr.io/sieteunoseis/cucm-soap-rest:latest
    environment:
      - NODE_ENV=production
      - CUCM_HOST=${CUCM_HOST}
      - CUCM_USER=${CUCM_USER}
      - CUCM_PASS=${CUCM_PASS}
      - CUCM_VERSION=${CUCM_VERSION}
      - PORT=3000
      - DATACONTAINERIDENTIFIERTAILS=_data
      - DEBUG=false
      - USE_API_KEY=true
      - API_KEY_NAME=x-api-key
      - API_KEY_LOCATION=header
      - AUTO_SAVE_EXAMPLES=${AUTO_SAVE_EXAMPLES:-false}
      - AUTO_SAVE_EXPLORER=${AUTO_SAVE_EXPLORER:-false}
    restart: always
    volumes:
      # Mount examples directory to allow customization without rebuilding the image
      - ../examples:/usr/src/app/src/examples
    networks:
      - kong-net
  kong:
    image: kong:latest
    container_name: kong-api-gateway
    depends_on:
      - cucm-rest-api
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/etc/kong/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
    volumes:
      - ./kong.yml:/etc/kong/kong.yml
    ports:
      - "8000:8000"  # Kong proxy
    restart: always
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge