_format_version: "2.1"
_transform: true

services:
  - name: cucm-api
    url: http://cucm-rest-api:3000
    routes:
      # Route for Swagger UI
      - name: swagger-ui-route
        paths:
          - /
        strip_path: false

      # Route for API endpoints
      - name: api-route
        paths:
          - /api/axl/
        strip_path: false
        plugins:
          # Authentication
          - name: key-auth
            config:
              hide_credentials: false
              key_names: ["apikey", "x-api-key"]
          
          # AXL-aware rate limiting
          - name: rate-limiting
            config:
              second: 5  # 5 requests per second max (adjust to match AXL limits)
              minute: 60  # 60 requests per minute
              hour: 1000
              policy: local
              limit_by: consumer  # Rate limit per API key/consumer
              redis_timeout: 2000  # If using Redis for distributed rate limiting
              fault_tolerant: true
              hide_client_headers: false
          
          # Request size limiting - AXL requests can be large
          - name: request-size-limiting
            config:
              allowed_payload_size: 2  # 2MB (adjust based on your largest AXL requests)
          
          # Response timeout handling
          - name: proxy-cache
            config:
              response_code: [200, 301, 302, 404, 451]
              request_method: ["GET", "HEAD"]
              content_type: ["text/plain", "application/json"]
              cache_ttl: 300
              strategy: memory
          
          # Circuit breaker for AXL server protection
          - name: circuit-breaker
            config:
              trip_threshold: 10
              error_threshold_percentage: 50
              healthy_interval: 5
              unhealthy_interval: 10
              unhealthy_statuses: [429, 500, 503]
              unhealthy_timeout: 60

consumers:
  # Regular user with standard limits
  - username: api-user
    keyauth_credentials:
      - key: your-secret-api-key
  
  # Power user with higher limits (if needed)
  - username: power-user
    keyauth_credentials:
      - key: power-user-api-key
    plugins:
      - name: rate-limiting
        config:
          second: 10  # Higher limit for power users
          minute: 120
          hour: 2000
          policy: local