name: Build and Push Docker Image

on:
  push:
    branches: [ master ]
    paths-ignore:
      # Documentation and markdown files
      - '**/*.md'
      - 'docs/**'
      
      # Images
      - 'screenshots/**'
      - 'public/logo.png'
      - 'public/favicon.ico'
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.jpeg'
      - '**/*.gif'
      - '**/*.svg'
      - '**/*.webp'
      
      # Configuration files that don't affect the build
      - 'nodemon.json'
      
      # Test files if they don't affect the build
      - 'test/**'
      
      # Docker-related files that don't affect the actual container build
      - 'docker/kong/**'
      - 'docker/README.md'
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}